---
# Create the internal Docker bridge network
- debug:
    msg: Create docker network on subnet - "{{subnet}}"

- name: Create Docker network
  docker_network:
    name: syntropynet
    driver: bridge
    ipam_config:
      - subnet: "{{subnet}}"
    retries: 2
    delay: 10
