---
# launch grafana

- name: Create persistent storage directory
  file:
    path: ~/data/grafana
    state: directory
    mode: "0755"

- name: Run grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    purge_networks: yes
    env:
      VIRTUAL_HOST: "{{duck_dns_domain}}"
      VIRTUAL_PORT: "3000"
      LETSENCRYPT_HOST: "{{duck_dns_domain}}"
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
      GF_SECURITY_ADMIN_USER: "{{grafana_login}}"
      GF_SECURITY_ADMIN_PASSWORD: "{{grafana_password}}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ~/data/grafana:/var/lib/grafana
    networks:
      - name: syntropynet
